# Generated by Django 4.0.2 on 2022-03-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_poliklinik_jadwalpraktek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.TextField()),
                ('gender', models.TextField()),
                ('nik', models.TextField()),
                ('address', models.TextField()),
                ('telp', models.TextField()),
                ('bpjs', models.TextField()),
                ('medical_record', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasien_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
