# Generated by Django 4.0.2 on 2022-03-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pasien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('poliklinik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antrian_poli', to='api.poliklinik')),
            ],
        ),
    ]
